#ifndef BOOST_DESCRIBE_DETAIL_PP_FOR_EACH_HPP_INCLUDED
#define BOOST_DESCRIBE_DETAIL_PP_FOR_EACH_HPP_INCLUDED

// Copyright 2020 Peter Dimov
// Distributed under the Boost Software License, Version 1.0.
// https://www.boost.org/LICENSE_1_0.txt

#include <boost/describe/detail/pp_utilities.hpp>

#define BOOST_DESCRIBE_PP_FOR_EACH_0(F, a)
#define BOOST_DESCRIBE_PP_FOR_EACH_1(F, a, x) BOOST_DESCRIBE_PP_CALL(F, a, x)
#define BOOST_DESCRIBE_PP_FOR_EACH_2(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_1(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_3(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_2(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_4(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_3(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_5(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_4(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_6(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_5(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_7(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_6(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_8(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_7(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_9(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_8(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_10(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_9(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_11(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_10(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_12(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_11(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_13(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_12(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_14(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_13(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_15(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_14(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_16(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_15(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_17(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_16(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_18(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_17(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_19(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_18(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_20(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_19(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_21(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_20(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_22(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_21(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_23(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_22(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_24(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_23(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_25(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_24(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_26(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_25(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_27(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_26(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_28(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_27(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_29(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_28(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_30(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_29(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_31(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_30(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_32(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_31(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_33(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_32(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_34(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_33(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_35(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_34(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_36(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_35(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_37(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_36(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_38(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_37(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_39(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_38(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_40(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_39(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_41(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_40(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_42(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_41(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_43(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_42(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_44(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_43(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_45(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_44(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_46(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_45(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_47(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_46(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_48(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_47(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_49(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_48(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_50(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_49(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_51(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_50(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_52(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_51(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_53(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_52(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_54(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_53(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_55(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_54(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_56(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_55(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_57(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_56(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_58(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_57(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_59(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_58(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_60(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_59(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_61(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_60(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_62(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_61(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_63(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_62(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_64(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_63(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_65(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_64(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_66(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_65(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_67(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_66(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_68(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_67(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_69(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_68(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_70(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_69(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_71(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_70(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_72(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_71(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_73(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_72(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_74(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_73(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_75(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_74(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_76(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_75(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_77(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_76(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_78(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_77(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_79(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_78(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_80(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_79(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_81(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_80(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_82(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_81(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_83(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_82(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_84(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_83(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_85(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_84(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_86(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_85(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_87(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_86(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_88(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_87(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_89(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_88(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_90(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_89(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_91(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_90(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_92(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_91(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_93(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_92(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_94(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_93(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_95(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_94(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_96(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_95(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_97(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_96(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_98(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_97(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_99(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_98(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_100(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_99(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_101(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_100(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_102(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_101(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_103(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_102(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_104(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_103(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_105(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_104(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_106(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_105(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_107(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_106(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_108(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_107(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_109(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_108(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_110(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_109(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_111(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_110(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_112(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_111(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_113(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_112(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_114(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_113(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_115(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_114(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_116(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_115(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_117(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_116(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_118(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_117(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_119(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_118(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_120(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_119(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_121(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_120(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_122(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_121(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_123(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_122(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_124(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_123(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_125(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_124(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_126(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_125(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_127(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_126(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_128(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_127(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_129(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_128(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_130(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_129(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_131(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_130(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_132(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_131(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_133(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_132(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_134(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_133(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_135(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_134(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_136(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_135(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_137(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_136(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_138(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_137(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_139(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_138(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_140(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_139(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_141(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_140(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_142(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_141(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_143(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_142(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_144(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_143(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_145(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_144(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_146(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_145(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_147(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_146(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_148(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_147(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_149(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_148(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_150(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_149(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_151(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_150(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_152(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_151(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_153(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_152(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_154(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_153(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_155(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_154(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_156(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_155(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_157(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_156(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_158(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_157(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_159(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_158(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_160(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_159(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_161(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_160(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_162(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_161(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_163(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_162(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_164(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_163(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_165(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_164(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_166(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_165(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_167(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_166(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_168(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_167(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_169(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_168(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_170(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_169(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_171(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_170(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_172(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_171(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_173(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_172(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_174(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_173(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_175(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_174(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_176(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_175(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_177(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_176(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_178(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_177(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_179(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_178(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_180(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_179(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_181(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_180(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_182(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_181(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_183(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_182(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_184(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_183(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_185(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_184(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_186(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_185(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_187(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_186(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_188(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_187(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_189(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_188(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_190(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_189(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_191(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_190(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_192(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_191(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_193(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_192(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_194(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_193(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_195(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_194(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_196(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_195(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_197(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_196(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_198(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_197(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_199(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_198(F, a, __VA_ARGS__))
#define BOOST_DESCRIBE_PP_FOR_EACH_200(F, a, x, ...) BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_CALL(F, a, x) BOOST_DESCRIBE_PP_FOR_EACH_199(F, a, __VA_ARGS__))

#define BOOST_DESCRIBE_PP_FE_EXTRACT(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63, _64, _65, _66, _67, _68, _69, _70, _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, _81, _82, _83, _84, _85, _86, _87, _88, _89, _90, _91, _92, _93, _94, _95, _96, _97, _98, _99, _100, _101, _102, _103, _104, _105, _106, _107, _108, _109, _110, _111, _112, _113, _114, _115, _116, _117, _118, _119, _120, _121, _122, _123, _124, _125, _126, _127, _128, _129, _130, _131, _132, _133, _134, _135, _136, _137, _138, _139, _140, _141, _142, _143, _144, _145, _146, _147, _148, _149, _150, _151, _152, _153, _154, _155, _156, _157, _158, _159, _160, _161, _162, _163, _164, _165, _166, _167, _168, _169, _170, _171, _172, _173, _174, _175, _176, _177, _178, _179, _180, _181, _182, _183, _184, _185, _186, _187, _188, _189, _190, _191, _192, _193, _194, _195, _196, _197, _198, _199, _200, V, ...) V

#define BOOST_DESCRIBE_PP_FOR_EACH(F, ...) \
    BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_EXPAND(BOOST_DESCRIBE_PP_FE_EXTRACT(__VA_ARGS__, \
    BOOST_DESCRIBE_PP_FOR_EACH_200, \
    BOOST_DESCRIBE_PP_FOR_EACH_199, \
    BOOST_DESCRIBE_PP_FOR_EACH_198, \
    BOOST_DESCRIBE_PP_FOR_EACH_197, \
    BOOST_DESCRIBE_PP_FOR_EACH_196, \
    BOOST_DESCRIBE_PP_FOR_EACH_195, \
    BOOST_DESCRIBE_PP_FOR_EACH_194, \
    BOOST_DESCRIBE_PP_FOR_EACH_193, \
    BOOST_DESCRIBE_PP_FOR_EACH_192, \
    BOOST_DESCRIBE_PP_FOR_EACH_191, \
    BOOST_DESCRIBE_PP_FOR_EACH_190, \
    BOOST_DESCRIBE_PP_FOR_EACH_189, \
    BOOST_DESCRIBE_PP_FOR_EACH_188, \
    BOOST_DESCRIBE_PP_FOR_EACH_187, \
    BOOST_DESCRIBE_PP_FOR_EACH_186, \
    BOOST_DESCRIBE_PP_FOR_EACH_185, \
    BOOST_DESCRIBE_PP_FOR_EACH_184, \
    BOOST_DESCRIBE_PP_FOR_EACH_183, \
    BOOST_DESCRIBE_PP_FOR_EACH_182, \
    BOOST_DESCRIBE_PP_FOR_EACH_181, \
    BOOST_DESCRIBE_PP_FOR_EACH_180, \
    BOOST_DESCRIBE_PP_FOR_EACH_179, \
    BOOST_DESCRIBE_PP_FOR_EACH_178, \
    BOOST_DESCRIBE_PP_FOR_EACH_177, \
    BOOST_DESCRIBE_PP_FOR_EACH_176, \
    BOOST_DESCRIBE_PP_FOR_EACH_175, \
    BOOST_DESCRIBE_PP_FOR_EACH_174, \
    BOOST_DESCRIBE_PP_FOR_EACH_173, \
    BOOST_DESCRIBE_PP_FOR_EACH_172, \
    BOOST_DESCRIBE_PP_FOR_EACH_171, \
    BOOST_DESCRIBE_PP_FOR_EACH_170, \
    BOOST_DESCRIBE_PP_FOR_EACH_169, \
    BOOST_DESCRIBE_PP_FOR_EACH_168, \
    BOOST_DESCRIBE_PP_FOR_EACH_167, \
    BOOST_DESCRIBE_PP_FOR_EACH_166, \
    BOOST_DESCRIBE_PP_FOR_EACH_165, \
    BOOST_DESCRIBE_PP_FOR_EACH_164, \
    BOOST_DESCRIBE_PP_FOR_EACH_163, \
    BOOST_DESCRIBE_PP_FOR_EACH_162, \
    BOOST_DESCRIBE_PP_FOR_EACH_161, \
    BOOST_DESCRIBE_PP_FOR_EACH_160, \
    BOOST_DESCRIBE_PP_FOR_EACH_159, \
    BOOST_DESCRIBE_PP_FOR_EACH_158, \
    BOOST_DESCRIBE_PP_FOR_EACH_157, \
    BOOST_DESCRIBE_PP_FOR_EACH_156, \
    BOOST_DESCRIBE_PP_FOR_EACH_155, \
    BOOST_DESCRIBE_PP_FOR_EACH_154, \
    BOOST_DESCRIBE_PP_FOR_EACH_153, \
    BOOST_DESCRIBE_PP_FOR_EACH_152, \
    BOOST_DESCRIBE_PP_FOR_EACH_151, \
    BOOST_DESCRIBE_PP_FOR_EACH_150, \
    BOOST_DESCRIBE_PP_FOR_EACH_149, \
    BOOST_DESCRIBE_PP_FOR_EACH_148, \
    BOOST_DESCRIBE_PP_FOR_EACH_147, \
    BOOST_DESCRIBE_PP_FOR_EACH_146, \
    BOOST_DESCRIBE_PP_FOR_EACH_145, \
    BOOST_DESCRIBE_PP_FOR_EACH_144, \
    BOOST_DESCRIBE_PP_FOR_EACH_143, \
    BOOST_DESCRIBE_PP_FOR_EACH_142, \
    BOOST_DESCRIBE_PP_FOR_EACH_141, \
    BOOST_DESCRIBE_PP_FOR_EACH_140, \
    BOOST_DESCRIBE_PP_FOR_EACH_139, \
    BOOST_DESCRIBE_PP_FOR_EACH_138, \
    BOOST_DESCRIBE_PP_FOR_EACH_137, \
    BOOST_DESCRIBE_PP_FOR_EACH_136, \
    BOOST_DESCRIBE_PP_FOR_EACH_135, \
    BOOST_DESCRIBE_PP_FOR_EACH_134, \
    BOOST_DESCRIBE_PP_FOR_EACH_133, \
    BOOST_DESCRIBE_PP_FOR_EACH_132, \
    BOOST_DESCRIBE_PP_FOR_EACH_131, \
    BOOST_DESCRIBE_PP_FOR_EACH_130, \
    BOOST_DESCRIBE_PP_FOR_EACH_129, \
    BOOST_DESCRIBE_PP_FOR_EACH_128, \
    BOOST_DESCRIBE_PP_FOR_EACH_127, \
    BOOST_DESCRIBE_PP_FOR_EACH_126, \
    BOOST_DESCRIBE_PP_FOR_EACH_125, \
    BOOST_DESCRIBE_PP_FOR_EACH_124, \
    BOOST_DESCRIBE_PP_FOR_EACH_123, \
    BOOST_DESCRIBE_PP_FOR_EACH_122, \
    BOOST_DESCRIBE_PP_FOR_EACH_121, \
    BOOST_DESCRIBE_PP_FOR_EACH_120, \
    BOOST_DESCRIBE_PP_FOR_EACH_119, \
    BOOST_DESCRIBE_PP_FOR_EACH_118, \
    BOOST_DESCRIBE_PP_FOR_EACH_117, \
    BOOST_DESCRIBE_PP_FOR_EACH_116, \
    BOOST_DESCRIBE_PP_FOR_EACH_115, \
    BOOST_DESCRIBE_PP_FOR_EACH_114, \
    BOOST_DESCRIBE_PP_FOR_EACH_113, \
    BOOST_DESCRIBE_PP_FOR_EACH_112, \
    BOOST_DESCRIBE_PP_FOR_EACH_111, \
    BOOST_DESCRIBE_PP_FOR_EACH_110, \
    BOOST_DESCRIBE_PP_FOR_EACH_109, \
    BOOST_DESCRIBE_PP_FOR_EACH_108, \
    BOOST_DESCRIBE_PP_FOR_EACH_107, \
    BOOST_DESCRIBE_PP_FOR_EACH_106, \
    BOOST_DESCRIBE_PP_FOR_EACH_105, \
    BOOST_DESCRIBE_PP_FOR_EACH_104, \
    BOOST_DESCRIBE_PP_FOR_EACH_103, \
    BOOST_DESCRIBE_PP_FOR_EACH_102, \
    BOOST_DESCRIBE_PP_FOR_EACH_101, \
    BOOST_DESCRIBE_PP_FOR_EACH_100, \
    BOOST_DESCRIBE_PP_FOR_EACH_99, \
    BOOST_DESCRIBE_PP_FOR_EACH_98, \
    BOOST_DESCRIBE_PP_FOR_EACH_97, \
    BOOST_DESCRIBE_PP_FOR_EACH_96, \
    BOOST_DESCRIBE_PP_FOR_EACH_95, \
    BOOST_DESCRIBE_PP_FOR_EACH_94, \
    BOOST_DESCRIBE_PP_FOR_EACH_93, \
    BOOST_DESCRIBE_PP_FOR_EACH_92, \
    BOOST_DESCRIBE_PP_FOR_EACH_91, \
    BOOST_DESCRIBE_PP_FOR_EACH_90, \
    BOOST_DESCRIBE_PP_FOR_EACH_89, \
    BOOST_DESCRIBE_PP_FOR_EACH_88, \
    BOOST_DESCRIBE_PP_FOR_EACH_87, \
    BOOST_DESCRIBE_PP_FOR_EACH_86, \
    BOOST_DESCRIBE_PP_FOR_EACH_85, \
    BOOST_DESCRIBE_PP_FOR_EACH_84, \
    BOOST_DESCRIBE_PP_FOR_EACH_83, \
    BOOST_DESCRIBE_PP_FOR_EACH_82, \
    BOOST_DESCRIBE_PP_FOR_EACH_81, \
    BOOST_DESCRIBE_PP_FOR_EACH_80, \
    BOOST_DESCRIBE_PP_FOR_EACH_79, \
    BOOST_DESCRIBE_PP_FOR_EACH_78, \
    BOOST_DESCRIBE_PP_FOR_EACH_77, \
    BOOST_DESCRIBE_PP_FOR_EACH_76, \
    BOOST_DESCRIBE_PP_FOR_EACH_75, \
    BOOST_DESCRIBE_PP_FOR_EACH_74, \
    BOOST_DESCRIBE_PP_FOR_EACH_73, \
    BOOST_DESCRIBE_PP_FOR_EACH_72, \
    BOOST_DESCRIBE_PP_FOR_EACH_71, \
    BOOST_DESCRIBE_PP_FOR_EACH_70, \
    BOOST_DESCRIBE_PP_FOR_EACH_69, \
    BOOST_DESCRIBE_PP_FOR_EACH_68, \
    BOOST_DESCRIBE_PP_FOR_EACH_67, \
    BOOST_DESCRIBE_PP_FOR_EACH_66, \
    BOOST_DESCRIBE_PP_FOR_EACH_65, \
    BOOST_DESCRIBE_PP_FOR_EACH_64, \
    BOOST_DESCRIBE_PP_FOR_EACH_63, \
    BOOST_DESCRIBE_PP_FOR_EACH_62, \
    BOOST_DESCRIBE_PP_FOR_EACH_61, \
    BOOST_DESCRIBE_PP_FOR_EACH_60, \
    BOOST_DESCRIBE_PP_FOR_EACH_59, \
    BOOST_DESCRIBE_PP_FOR_EACH_58, \
    BOOST_DESCRIBE_PP_FOR_EACH_57, \
    BOOST_DESCRIBE_PP_FOR_EACH_56, \
    BOOST_DESCRIBE_PP_FOR_EACH_55, \
    BOOST_DESCRIBE_PP_FOR_EACH_54, \
    BOOST_DESCRIBE_PP_FOR_EACH_53, \
    BOOST_DESCRIBE_PP_FOR_EACH_52, \
    BOOST_DESCRIBE_PP_FOR_EACH_51, \
    BOOST_DESCRIBE_PP_FOR_EACH_50, \
    BOOST_DESCRIBE_PP_FOR_EACH_49, \
    BOOST_DESCRIBE_PP_FOR_EACH_48, \
    BOOST_DESCRIBE_PP_FOR_EACH_47, \
    BOOST_DESCRIBE_PP_FOR_EACH_46, \
    BOOST_DESCRIBE_PP_FOR_EACH_45, \
    BOOST_DESCRIBE_PP_FOR_EACH_44, \
    BOOST_DESCRIBE_PP_FOR_EACH_43, \
    BOOST_DESCRIBE_PP_FOR_EACH_42, \
    BOOST_DESCRIBE_PP_FOR_EACH_41, \
    BOOST_DESCRIBE_PP_FOR_EACH_40, \
    BOOST_DESCRIBE_PP_FOR_EACH_39, \
    BOOST_DESCRIBE_PP_FOR_EACH_38, \
    BOOST_DESCRIBE_PP_FOR_EACH_37, \
    BOOST_DESCRIBE_PP_FOR_EACH_36, \
    BOOST_DESCRIBE_PP_FOR_EACH_35, \
    BOOST_DESCRIBE_PP_FOR_EACH_34, \
    BOOST_DESCRIBE_PP_FOR_EACH_33, \
    BOOST_DESCRIBE_PP_FOR_EACH_32, \
    BOOST_DESCRIBE_PP_FOR_EACH_31, \
    BOOST_DESCRIBE_PP_FOR_EACH_30, \
    BOOST_DESCRIBE_PP_FOR_EACH_29, \
    BOOST_DESCRIBE_PP_FOR_EACH_28, \
    BOOST_DESCRIBE_PP_FOR_EACH_27, \
    BOOST_DESCRIBE_PP_FOR_EACH_26, \
    BOOST_DESCRIBE_PP_FOR_EACH_25, \
    BOOST_DESCRIBE_PP_FOR_EACH_24, \
    BOOST_DESCRIBE_PP_FOR_EACH_23, \
    BOOST_DESCRIBE_PP_FOR_EACH_22, \
    BOOST_DESCRIBE_PP_FOR_EACH_21, \
    BOOST_DESCRIBE_PP_FOR_EACH_20, \
    BOOST_DESCRIBE_PP_FOR_EACH_19, \
    BOOST_DESCRIBE_PP_FOR_EACH_18, \
    BOOST_DESCRIBE_PP_FOR_EACH_17, \
    BOOST_DESCRIBE_PP_FOR_EACH_16, \
    BOOST_DESCRIBE_PP_FOR_EACH_15, \
    BOOST_DESCRIBE_PP_FOR_EACH_14, \
    BOOST_DESCRIBE_PP_FOR_EACH_13, \
    BOOST_DESCRIBE_PP_FOR_EACH_12, \
    BOOST_DESCRIBE_PP_FOR_EACH_11, \
    BOOST_DESCRIBE_PP_FOR_EACH_10, \
    BOOST_DESCRIBE_PP_FOR_EACH_9, \
    BOOST_DESCRIBE_PP_FOR_EACH_8, \
    BOOST_DESCRIBE_PP_FOR_EACH_7, \
    BOOST_DESCRIBE_PP_FOR_EACH_6, \
    BOOST_DESCRIBE_PP_FOR_EACH_5, \
    BOOST_DESCRIBE_PP_FOR_EACH_4, \
    BOOST_DESCRIBE_PP_FOR_EACH_3, \
    BOOST_DESCRIBE_PP_FOR_EACH_2, \
    BOOST_DESCRIBE_PP_FOR_EACH_1, \
    BOOST_DESCRIBE_PP_FOR_EACH_0))(F, __VA_ARGS__))

#endif // #ifndef BOOST_DESCRIBE_DETAIL_PP_FOR_EACH_HPP_INCLUDED
